
default: &default
  adapter: postgresql
  username: postgres
  password: 123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
